maya_commands = {2015:['aaf2fcp', 'about', 'addAttr', 'addDynamic', 'addExtension', 'addMetadata', 'addPP',
                      'affectedNet', 'affects', 'aimConstraint', 'air', 'aliasAttr', 'align', 'alignCtx', 'alignCurve',
                      'alignSurface', 'allNodeTypes', 'ambientLight', 'angleBetween', 'animCurveEditor', 'animDisplay',
                      'animLayer', 'animView', 'annotate', 'applyAttrPattern', 'applyMetadata', 'applyTake', 'arclen',
                      'arcLenDimContext', 'arcLengthDimension', 'arrayMapper', 'art3dPaintCtx', 'artAttrCtx',
                      'artAttrPaintVertexCtx', 'artAttrSkinPaintCtx', 'artAttrTool', 'artBuildPaintMen',
                      'artFluidAttrCtx', 'artPuttyCtx', 'artSelectCtx', 'artSetPaintCtx', 'artUserPaintCtx', 'assembly',
                      'assignCommand', 'assignInputDevice', 'assignViewportFactories', 'attachCurve',
                      'attachDeviceAttr', 'attachSurface', 'attrColorSliderGrp', 'attrCompatibility', 'attrControlGrp',
                      'attrEnumOptionMen', 'attrEnumOptionMenuGrp', 'attrFieldGrp', 'attrFieldSliderGrp',
                      'attributeInfo', 'attributeMen', 'attributeName', 'attributeQuery', 'attrNavigationControlGrp',
                      'audioTrack', 'autoKeyframe', 'autoPlace', 'autoSave', 'bakeClip', 'bakePartialHistory',
                      'bakeResults', 'bakeSimulation', 'baseTemplate', 'baseView', 'batchRender', 'bevel', 'bevelPlus',
                      'bezierAnchorPreset', 'bezierAnchorState', 'bezierCurveToNurbs', 'bezierInfo', 'bindSkin',
                      'binMembership', 'blend2', 'blendShape', 'blendShapeEditor', 'blendShapePanel', 'blendTwoAttr',
                      'blindDataType', 'boneLattice', 'boundary', 'boxDollyCtx', 'boxZoomCtx', 'bufferCurve',
                      'buildBookmarkMen', 'buildKeyframeMen', 'button', 'buttonManip', 'cacheFile', 'cacheFileCombine',
                      'cacheFileMerge', 'cacheFileTrack', 'callbacks', 'camera', 'cameraSet', 'cameraView',
                      'canCreateManip', 'canvas', 'changeSubdivComponentDisplayLevel', 'changeSubdivRegion',
                      'channelBox', 'character', 'characterize', 'characterMap', 'checkBox', 'checkBoxGrp',
                      'checkDefaultRenderGlobals', 'choice', 'circle', 'circularFillet', 'clearCache', 'clip',
                      'clipEditor', 'clipEditorCurrentTimeCtx', 'clipMatching', 'clipSchedule', 'clipSchedulerOutliner',
                      'closeCurve', 'closeSurface', 'cluster', 'cmdFileOutput', 'cmdScrollFieldExecuter',
                      'cmdScrollFieldReporter', 'cmdShell', 'coarsenSubdivSelectionList', 'collision', 'color',
                      'colorAtPoint', 'colorEditor', 'colorIndex', 'colorIndexSliderGrp', 'colorManagementCatalog',
                      'colorManagementPrefs', 'colorSliderButtonGrp', 'colorSliderGrp', 'columnLayout', 'commandEcho',
                      'commandLine', 'commandLogging', 'commandPort', 'componentBox', 'componentEditor', 'condition',
                      'cone', 'confirmDialog', 'connectAttr', 'connectControl', 'connectDynamic', 'connectionInfo',
                      'connectJoint', 'constrain', 'constructionHistory', 'container', 'containerBind',
                      'containerProxy', 'containerPublish', 'containerTemplate', 'containerView', 'contextInfo',
                      'control', 'convertIffToPsd', 'convertLightmap', 'convertSolidTx', 'convertTessellation',
                      'convertUnit', 'copyAttr', 'copyDeformerWeights', 'copyFlexor', 'copyKey', 'copySkinWeights',
                      'createAttrPatterns', 'createDisplayLayer', 'createEditor', 'createLayeredPsdFile', 'createNode',
                      'createRenderLayer', 'createSubdivRegion', 'ctxAbort', 'ctxCompletion', 'ctxEditMode',
                      'ctxTraverse', 'currentCtx', 'currentTime', 'currentTimeCtx', 'currentUnit', 'curve',
                      'curveAddPtCtx', 'curveCVCtx', 'curveEditorCtx', 'curveEPCtx', 'curveIntersect', 'curveMoveEPCtx',
                      'curveOnSurface', 'curveRGBColor', 'curveSketchCtx', 'cutKey', 'cycleCheck', 'cylinder',
                      'dagObjectCompare', 'dagPose', 'dataStructure', 'date', 'dbcount', 'dbmessage', 'dbpeek',
                      'defaultLightListCheckBox', 'defaultNavigation', 'defineDataServer', 'defineVirtualDevice',
                      'deformer', 'deformerWeights', 'delete', 'deleteAttr', 'deleteAttrPattern', 'deleteExtension',
                      'deleteUI', 'detachCurve', 'detachDeviceAttr', 'detachSurface', 'deviceEditor', 'deviceManager',
                      'devicePanel', 'dgdirty', 'dgeval', 'dgInfo', 'dgmodified', 'dgtimer', 'dimWhen',
                      'directionalLight', 'directKeyCtx', 'dirmap', 'disable', 'disableIncorrectNameWarning',
                      'disconnectAttr', 'disconnectJoint', 'diskCache', 'displacementToPoly', 'displayAffected',
                      'displayColor', 'displayCull', 'displayLevelOfDetail', 'displayPref', 'displayRGBColor',
                      'displaySmoothness', 'displayStats', 'displayString', 'displaySurface', 'distanceDimContext',
                      'distanceDimension', 'doBlur', 'dockControl', 'dolly', 'dollyCtx', 'dopeSheetEditor',
                      'doubleProfileBirailSurface', 'drag', 'dragAttrContext', 'draggerContext', 'dropoffLocator',
                      'duplicate', 'duplicateCurve', 'duplicateSurface', 'dynamicLoad', 'dynCache', 'dynControl',
                      'dynExport', 'dynExpression', 'dynGlobals', 'dynPaintEditor', 'dynParticleCtx', 'dynPref',
                      'editDisplayLayerGlobals', 'editDisplayLayerMembers', 'editMetadata', 'editor', 'editorTemplate',
                      'editRenderLayerAdjustment', 'editRenderLayerGlobals', 'editRenderLayerMembers', 'effector',
                      'emit', 'emitter', 'enableDevice', 'encodeString', 'error', 'eval', 'evalDeferred', 'event',
                      'exactWorldBoundingBox', 'exclusiveLightCheckBox', 'exportEdits', 'expression',
                      'expressionEditorListen', 'extendCurve', 'extendSurface', 'extrude', 'fcheck', 'file',
                      'fileBrowserDialog', 'fileDialog', 'fileDialog2', 'fileInfo', 'filePathEditor', 'filletCurve',
                      'filter', 'filterCurve', 'filterExpand', 'filterStudioImport', 'findKeyframe', 'findType',
                      'fitBspline', 'flexor', 'floatField', 'floatFieldGrp', 'floatScrollBar', 'floatSlider',
                      'floatSlider2', 'floatSliderButtonGrp', 'floatSliderGrp', 'flow', 'flowLayout', 'fluidCacheInfo',
                      'fluidEmitter', 'fluidVoxelInfo', 'flushUndo', 'fontDialog', 'format', 'formLayout',
                      'frameBufferName', 'frameLayout', 'freeFormFillet', 'geomBind', 'geometryConstraint',
                      'geomToBBox', 'getAttr', 'getClassification', 'getDefaultBrush', 'getFileList', 'getFluidAttr',
                      'getInputDeviceRange', 'getMetadata', 'getModifiers', 'getModulePath', 'getPanel',
                      'getParticleAttr', 'getRenderDependencies', 'getRenderTasks', 'globalStitch', 'glRender',
                      'glRenderEditor', 'goal', 'grabColor', 'gradientControl', 'gradientControlNoAttr',
                      'graphDollyCtx', 'graphSelectContext', 'graphTrackCtx', 'gravity', 'greasePencilCtx', 'grid',
                      'gridLayout', 'group', 'hardenPointCurve', 'hardware', 'hardwareRenderPanel', 'hasMetadata',
                      'headsUpDisplay', 'headsUpMessage', 'help', 'helpLine', 'hide', 'hikGlobals', 'hilite', 'hitTest',
                      'hotBox', 'hotkey', 'hotkeyCheck', 'hudButton', 'hudSlider', 'hudSliderButton', 'hwReflectionMap',
                      'hwRender', 'hwRenderLoad', 'hyperGraph', 'hyperPanel', 'hyperShade', 'iconTextButton',
                      'iconTextCheckBox', 'iconTextRadioButton', 'iconTextRadioCollection', 'iconTextScrollList',
                      'iconTextStaticLabel', 'ikfkDisplayMethod', 'ikHandle', 'ikHandleCtx', 'ikHandleDisplayScale',
                      'ikSolver', 'ikSplineHandleCtx', 'ikSystem', 'ikSystemInfo', 'illustratorCurves', 'image',
                      'imagePlane', 'imfPlugins', 'inheritTransform', 'insertJoint', 'insertJointCtx', 'insertKeyCtx',
                      'insertKnotCurve', 'insertKnotSurface', 'instance', 'instanceable', 'instancer', 'internalVar',
                      'intersect', 'intField', 'intFieldGrp', 'intScrollBar', 'intSlider', 'intSliderGrp',
                      'inViewMessage', 'iprEngine', 'isConnected', 'isDirty', 'isolateSelect', 'isTrue', 'itemFilter',
                      'itemFilterAttr', 'itemFilterType', 'joint', 'jointCluster', 'jointCtx', 'jointDisplayScale',
                      'jointLattice', 'keyframe', 'keyframeOutliner', 'keyframeRegionCurrentTimeCtx',
                      'keyframeRegionDirectKeyCtx', 'keyframeRegionDollyCtx', 'keyframeRegionInsertKeyCtx',
                      'keyframeRegionMoveKeyCtx', 'keyframeRegionScaleKeyCtx', 'keyframeRegionSelectKeyCtx',
                      'keyframeRegionSetKeyCtx', 'keyframeRegionTrackCtx', 'keyframeStats', 'keyingGroup', 'keyTangent',
                      'lassoContext', 'lattice', 'latticeDeformKeyCtx', 'launch', 'launchImageEditor', 'layerButton',
                      'layeredShaderPort', 'layeredTexturePort', 'layout', 'layoutDialog', 'license', 'lightlink',
                      'lightList', 'linearPrecision', 'listAnimatable', 'listAttr', 'listAttrPatterns', 'listCameras',
                      'listConnections', 'listDeviceAttachments', 'listHistory', 'listInputDeviceAxes',
                      'listInputDeviceButtons', 'listInputDevices', 'listNodesWithIncorrectNames', 'listNodeTypes',
                      'listRelatives', 'listSets', 'loadFluid', 'loadModule', 'loadPlugin', 'loadPrefObjects', 'loadUI',
                      'lockNode', 'loft', 'lookThr', 'ls', 'lsThroughFilter', 'lsUI', 'makebot', 'makeIdentity',
                      'makeLive', 'makePaintable', 'makeSingleSurface', 'manipMoveContext', 'manipMoveLimitsCtx',
                      'manipOptions', 'manipPivot', 'manipRotateContext', 'manipRotateLimitsCtx', 'manipScaleContext',
                      'manipScaleLimitsCtx', 'marker', 'Mayatomr', 'melInfo', 'memory', 'men', 'menuBarLayout',
                      'menuEditor', 'menuItem', 'menuSet', 'menuSetPref', 'messageLine', 'minimizeApp', 'mirrorJoint',
                      'modelCurrentTimeCtx', 'modelEditor', 'modelPanel', 'moduleInfo', 'mouse', 'move', 'moveKeyCtx',
                      'moveVertexAlongDirection', 'movieInfo', 'movIn', 'movOut', 'multiProfileBirailSurface',
                      'multiTouch', 'mute', 'nameCommand', 'nameField', 'namespace', 'namespaceInfo', 'nBase', 'newton',
                      'nodeCast', 'nodeEditor', 'nodeIconButton', 'nodeOutliner', 'nodePreset', 'nodeTreeLister',
                      'nodeType', 'nonLinear', 'normalConstraint',
                      'nParticle', 'nurbsBoolean', 'nurbsCopyUVSet', 'nurbsCube', 'nurbsCurveToBezier', 'nurbsEditUV',
                      'nurbsPlane', 'nurbsSelect', 'nurbsSquare', 'nurbsToPoly', 'nurbsToPolygonsPref', 'nurbsToSubdiv',
                      'nurbsToSubdivPref', 'nurbsUVSet', 'objectCenter', 'objectType', 'objectTypeUI', 'objExists',
                      'offsetCurve', 'offsetCurveOnSurface', 'offsetSurface', 'ogs', 'ogsRender', 'openGLExtension',
                      'openMayaPref', 'optionMen', 'optionMenuGrp', 'optionVar', 'orbit', 'orbitCtx',
                      'orientConstraint', 'outlinerEditor', 'outlinerPanel', 'overrideModifier', 'paintEffectsDisplay',
                      'pairBlend', 'palettePort', 'panel', 'paneLayout', 'panelConfiguration', 'panelHistory',
                      'panZoom', 'panZoomCtx', 'paramDimContext', 'paramDimension', 'paramLocator', 'parent',
                      'parentConstraint', 'particle', 'particleExists', 'particleFill', 'particleInstancer',
                      'particleRenderInfo', 'partition', 'pasteKey', 'pathAnimation', 'pause', 'perCameraVisibility',
                      'percent', 'performanceOptions', 'pfxstrokes', 'pickWalk', 'picture', 'pixelMove', 'planarSrf',
                      'plane', 'play', 'playbackOptions', 'playblast', 'pluginDisplayFilter', 'pluginInfo',
                      'pointConstraint', 'pointCurveConstraint', 'pointLight', 'pointOnCurve', 'pointOnPolyConstraint',
                      'pointOnSurface', 'pointPosition', 'poleVectorConstraint', 'polyAppend', 'polyAppendFacetCtx',
                      'polyAppendVertex', 'polyAutoProjection', 'polyAverageNormal', 'polyAverageVertex', 'polyBevel',
                      'polyBlendColor', 'polyBlindData', 'polyBoolOp', 'polyBridgeEdge', 'polyCacheMonitor',
                      'polyCBoolOp', 'polyCheck', 'polyChipOff', 'polyClipboard', 'polyCloseBorder', 'polyCollapseEdge',
                      'polyCollapseFacet', 'polyColorBlindData', 'polyColorDel', 'polyColorMod', 'polyColorPerVertex',
                      'polyColorSet', 'polyCompare', 'polyCone', 'polyConnectComponents', 'polyCopyUV', 'polyCrease',
                      'polyCreaseCtx', 'polyCreateFacet', 'polyCreateFacetCtx', 'polyCube', 'polyCut', 'polyCutCtx',
                      'polyCylinder', 'polyCylindricalProjection', 'polyDelEdge', 'polyDelFacet', 'polyDelVertex',
                      'polyDuplicateAndConnect', 'polyDuplicateEdge', 'polyEditEdgeFlow', 'polyEditUV',
                      'polyEditUVShell', 'polyEvaluate', 'polyExtrudeEdge', 'polyExtrudeFacet', 'polyExtrudeVertex',
                      'polyFlipEdge', 'polyFlipUV', 'polyForceUV', 'polyGeoSampler', 'polyHelix', 'polyHole',
                      'polyInfo', 'polyInstallAction', 'polyLayoutUV', 'polyListComponentConversion', 'polyMapCut',
                      'polyMapDel', 'polyMapSew', 'polyMapSewMove', 'polyMergeEdge', 'polyMergeEdgeCtx',
                      'polyMergeFacet', 'polyMergeFacetCtx', 'polyMergeUV', 'polyMergeVertex', 'polyMirrorFace',
                      'polyMoveEdge', 'polyMoveFacet', 'polyMoveFacetUV', 'polyMoveUV', 'polyMoveVertex',
                      'polyMultiLayoutUV', 'polyNormal', 'polyNormalizeUV', 'polyNormalPerVertex', 'polyOptions',
                      'polyOptUvs', 'polyOutput', 'polyPipe', 'polyPlanarProjection', 'polyPlane', 'polyPlatonicSolid',
                      'polyPoke', 'polyPrimitive', 'polyPrism', 'polyProjectCurve', 'polyProjection', 'polyPyramid',
                      'polyQuad', 'polyQueryBlindData', 'polyReduce', 'polySelect', 'polySelectConstraint',
                      'polySelectConstraintMonitor', 'polySelectCtx', 'polySelectEditCtx', 'polySeparate',
                      'polySetToFaceNormal', 'polySewEdge', 'polyShortestPathCtx', 'polySlideEdge', 'polySmooth',
                      'polySoftEdge', 'polySphere', 'polySphericalProjection', 'polySplit', 'polySplitCtx',
                      'polySplitCtx2', 'polySplitEdge', 'polySplitRing', 'polySplitVertex', 'polyStraightenUVBorder',
                      'polySubdivideEdge', 'polySubdivideFacet', 'polyTorus', 'polyToSubdiv', 'polyTransfer',
                      'polyTriangulate', 'polyUnite', 'polyUniteSkinned', 'polyUVRectangle', 'polyUVSet',
                      'polyWedgeFace', 'popupMen', 'pose', 'preloadRefEd', 'prepareRender', 'profiler', 'profilerTool',
                      'progressBar', 'progressWindow', 'projectCurve', 'projectionContext', 'projectionManip',
                      'projectTangent', 'promptDialog', 'propModCtx', 'propMove', 'psdChannelOutliner',
                      'psdEditTextureFile', 'psdExport', 'psdTextureFile', 'querySubdiv', 'quit', 'radial',
                      'radioButton', 'radioButtonGrp', 'radioCollection', 'radioMenuItemCollection', 'rampColorPort',
                      'rangeControl', 'readTake', 'rebuildCurve', 'rebuildSurface', 'recordAttr', 'recordDevice',
                      'redo', 'reference', 'referenceEdit', 'referenceQuery', 'refineSubdivSelectionList', 'refresh',
                      'refreshEditorTemplates', 'regionSelectKeyCtx', 'relationship', 'reloadImage', 'removeJoint',
                      'removeMultiInstance', 'rename', 'renameAttr', 'renameUI', 'render', 'renderer',
                      'renderGlobalsNode', 'renderInfo', 'renderLayerPostProcess', 'renderManip', 'renderPartition',
                      'renderPassRegistry', 'renderQualityNode', 'renderSettings', 'renderThumbnailUpdate',
                      'renderWindowEditor', 'renderWindowSelectContext', 'reorder', 'reorderContainer',
                      'reorderDeformers', 'requires', 'reroot', 'resampleFluid', 'resetTool', 'resolutionNode',
                      'resourceManager', 'retarget', 'retimeKeyCtx', 'reverseCurve', 'reverseSurface', 'revolve',
                      'rigidBody', 'rigidSolver', 'roll', 'rollCtx', 'rotate', 'rotationInterpolation',
                      'roundConstantRadius', 'rowColumnLayout', 'rowLayout', 'runup', 'sampleImage', 'saveAllShelves',
                      'saveFluid', 'saveImage', 'saveInitialState', 'saveMen', 'savePrefObjects', 'savePrefs',
                      'saveShelf', 'saveToolSettings', 'saveViewportSettings', 'scale', 'scaleComponents',
                      'scaleConstraint', 'scaleKey', 'scaleKeyCtx', 'sceneEditor', 'sceneUIReplacement', 'scmh',
                      'scriptCtx', 'scriptEditorInfo', 'scriptedPanel', 'scriptedPanelType', 'scriptJob', 'scriptNode',
                      'scriptTable', 'scrollField', 'scrollLayout', 'sculpt', 'select', 'selectContext',
                      'selectedNodes', 'selectionConnection', 'selectKey', 'selectKeyCtx', 'selectKeyframeRegionCtx',
                      'selectMode', 'selectPref', 'selectPriority', 'selectType', 'selLoadSettings', 'separator',
                      'sequenceManager', 'setAttr', 'setAttrMapping', 'setDefaultShadingGroup', 'setDrivenKeyframe',
                      'setDynamic', 'setEditCtx', 'setFluidAttr', 'setFocus', 'setInfinity', 'setInputDeviceMapping',
                      'setKeyCtx', 'setKeyframe', 'setKeyframeBlendshapeTargetWts', 'setKeyPath', 'setMenuMode',
                      'setNodeTypeFlag', 'setParent', 'setParticleAttr', 'setRenderPassType', 'sets',
                      'setStartupMessage', 'setToolTo', 'setUITemplate', 'setXformManip', 'shadingConnection',
                      'shadingGeometryRelCtx', 'shadingLightRelCtx', 'shadingNetworkCompare', 'shadingNode',
                      'shapeCompare', 'shelfButton', 'shelfLayout', 'shelfTabLayout', 'shot', 'shotRipple', 'shotTrack',
                      'showHelp', 'showHidden', 'showManipCtx', 'showSelectionInTitle', 'showShadingGroupAttrEditor',
                      'showWindow', 'simplify', 'singleProfileBirailSurface', 'skinBindCtx', 'skinCluster',
                      'skinPercent', 'smoothCurve', 'smoothTangentSurface', 'snapKey', 'snapMode', 'snapshot',
                      'snapshotBeadCtx', 'snapshotModifyKeyCtx', 'snapTogetherCtx', 'soft', 'softMod', 'softModCtx',
                      'softSelect', 'sound', 'soundControl', 'spaceLocator', 'sphere', 'spotLight',
                      'spotLightPreviewPort', 'spreadSheetEditor', 'spring', 'squareSurface', 'srtContext',
                      'stereoCameraView', 'stereoRigManager', 'stitchSurface', 'stitchSurfacePoints',
                      'stringArrayIntersector', 'stroke', 'subdAutoProjection', 'subdCleanTopology', 'subdCollapse',
                      'subdDuplicateAndConnect', 'subdEditUV', 'subdiv', 'subdivCrease', 'subdivDisplaySmoothness',
                      'subdLayoutUV', 'subdListComponentConversion', 'subdMapCut', 'subdMapSewMove',
                      'subdMatchTopology', 'subdMirror', 'subdPlanarProjection', 'subdToBlind', 'subdToPoly',
                      'subdTransferUVsToCache', 'substituteGeometry', 'suitePrefs', 'surface', 'surfaceSampler',
                      'surfaceShaderList', 'swatchDisplayPort', 'swatchRefresh', 'switchTable', 'symbolButton',
                      'symbolCheckBox', 'symmetricModelling', 'sysFile', 'tabLayout', 'tangentConstraint',
                      'targetWeldCtx', 'texLatticeDeformContext', 'texManipContext', 'texMoveContext',
                      'texMoveUVShellContext', 'texRotateContext', 'texScaleContext', 'texSelectContext',
                      'texSelectShortestPathCtx', 'texSmudgeUVContext', 'text', 'textCurves', 'textField',
                      'textFieldButtonGrp', 'textFieldGrp', 'textManip', 'textScrollList', 'textureDeformer',
                      'texturePlacementContext', 'textureWindow', 'texTweakUVContext', 'texWinToolCtx', 'threadCount',
                      'threePointArcCtx', 'timeCode', 'timeControl', 'timePort', 'timer', 'timerX', 'timeWarp',
                      'toggle', 'toggleAxis', 'toggleWindowVisibility', 'tolerance', 'toolBar', 'toolButton',
                      'toolCollection', 'toolDropped', 'toolHasOptions', 'toolPropertyWindow', 'torus', 'track',
                      'trackCtx', 'transferAttributes', 'transferShadingSets', 'transformCompare', 'transformLimits',
                      'translator', 'treeLister', 'treeView', 'trim', 'truncateFluidCache', 'truncateHairCache',
                      'tumble', 'tumbleCtx', 'turbulence', 'twoPointArcCtx', 'ubercam', 'uiTemplate',
                      'unassignInputDevice', 'undo', 'undoInfo', 'unfold', 'ungroup', 'uniform', 'unloadPlugin',
                      'untangleUV', 'untrim', 'upAxis', 'userCtx', 'uvLink', 'uvSnapshot', 'vectorize', 'view2dToolCtx',
                      'viewCamera', 'viewClipPlane', 'viewFit', 'viewHeadOn', 'viewLookAt', 'viewManip', 'viewPlace',
                      'viewSet', 'visor', 'volumeAxis', 'volumeBind', 'vortex', 'waitCursor', 'walkCtx', 'warning',
                      'webBrowser', 'webBrowserPrefs', 'webView', 'whatsNewHighlight', 'window', 'windowPref', 'wire',
                      'wireContext', 'workspace', 'wrinkle', 'wrinkleContext', 'writeTake', 'xform', 'xpmPicker']}
